name: Run tests
description: Run tests for a single matrix entry
inputs:
  endtoend:
    type: boolean
    default: false
  # if endtoend_suite is blank it will run suites defined in root behat.yml
  # this is only required for extra_jobs running non-root suites e.g. running asset-admin behat from silverstripe-installer
  endtoend_suite:
    type: string
    default: ''
  phpcoverage:
    type: boolean
    default: false
  phplinting:
    type: boolean
    default: false
  phpunit:
    type: boolean
    default: false
  phpunit_suite:
    type: string
    default: ''
  js:
    type: boolean
    default: false
runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      env:
        PHPUNIT_SUITE: ${{ inputs.phpunit_suite }}
        ENDTOEND_SUITE: ${{ inputs.endtoend_suite }}
      run: |
        if ! [[ "$PHPUNIT_SUITE" =~ ^[a-zA-Z0-9_\-]*$ ]]; then exit 1; fi
        if ! [[ "$ENDTOEND_SUITE" =~ ^[a-zA-Z0-9_\-]*$ ]]; then exit 1; fi
    - name: Run PHPUnit
      if: ${{ inputs.phpunit }}
      shell: bash
      env:
        PHPUNIT_SUITE: ${{ inputs.phpunit_suite }}
      run: |
        echo "Running PHPUnit"
        if [ "$PHPUNIT_SUITE" == "all" ]; then
          vendor/bin/phpunit --verbose --colors=always
        else
          vendor/bin/phpunit --verbose --colors=always --testsuite "$PHPUNIT_SUITE"
        fi
        echo "Passed"
    - name: Run end-to-end tests
      if: ${{ inputs.endtoend }}
      shell: bash
      env:
        ENDTOEND_SUITE: ${{ inputs.endtoend_suite }}
      run: |
        echo "Running behat"
        if [ ! -f behat.yml ]; then echo "behat.yml missing" && exit 1; fi
        if [ -f __behat.php ]; then rm __behat.php; fi
        if [ -f __behat_headless.yml ]; then rm __behat_headless.yml; fi
        cp ${{ github.action_path }}/behat.php __behat.php
        cp ${{ github.action_path }}/behat_headless.yml __behat_headless.yml
        php __behat.php
        rm __behat.php
        rm __behat_headless.yml
        nohup sh -c "chromedriver" > /dev/null 2>&1 &
        if [ "$ENDTOEND_SUITE" ]; then
          vendor/bin/behat --colors --strict "$ENDTOEND_SUITE"
        else
          vendor/bin/behat --colors --strict
        fi
        echo "Passed"
    - name: Run JS tests
      if: ${{ inputs.js }}
      shell: bash
      run: |
        echo "Running JS tests"
        if [ ! -f package.json ]; then echo "package.json missing" && exit 1; fi
        wget https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
        php -r "if (hash_file('sha384', 'install.sh') === 'dd4b116a7452fc3bb8c0e410ceac27e19b0ba0f900fe2f91818a95c12e92130fdfb8170fec170b9fb006d316f6386f2b') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('install.sh'); } echo PHP_EOL;"
        if [ ! -f install.sh ]; then echo "Cannot install nvm" && exit 1; fi
        . install.sh
        rm install.sh
        export NVM_DIR="$HOME/.nvm"
        # this loads nvm into the current terminal
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        if [ ! -f .nvmrc ]; then echo "Missing .nvmrc" && exit 1; fi
        nvm install
        nvm use
        rm -rf client/dist
        npm install -g yarn
        yarn install --network-concurrency 1
        if [ -d vendor/silverstripe/admin ]; then
          cd vendor/silverstripe/admin
          yarn install --network-concurrency 1
          cd ../../..
        fi
        yarn run build
        echo "Running git diff"
        git diff-files --quiet -w --relative=client
        git diff --name-status --relative=client
        echo "Running yarn test"
        yarn run test
        echo "Running yarn lint"
        yarn run lint
        echo "Passed"
    - name: "Run PHP linting"
      if: ${{ inputs.phplinting }}
      shell: bash
      run: |
        echo "Running PHPCS"
        if [ ! -f phpcs.xml.dist ]; then echo "Missing phpcs.xml.dist" && exit 1; fi
        vendor/bin/phpcs
        # phpstan is optional
        if [ -f phpstan.neon.dist ]; then
          echo "Running PHPStan"
          vendor/bin/phpstan analyse
        fi
        # cow validation is also done here due to it being a tiny piece of work not meriting its own step
        if [ -f .cow.json ]; then
          echo "Running cow schema validate"
          vendor/bin/cow schema:validate
        fi
        echo "Passed"
    - name: "Run PHP coverage"
      if: ${{ inputs.phpcoverage }}
      shell: bash
      run: |
        echo "Running codecov"
        curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import
        curl -Os https://uploader.codecov.io/latest/codecov-linux
        curl -Os https://uploader.codecov.io/latest/codecov-linux.SHA256SUM
        curl -Os https://uploader.codecov.io/latest/codecov-linux.SHA256SUM.sig
        gpg --verify codecov-linux.SHA256SUM.sig codecov-linux.SHA256SUM
        shasum -a 256 -c codecov-linux.SHA256SUM
        chmod +x codecov-linux
        phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
        ./codecov-linux -f coverage.xml;
        echo "coverage.xml generated and uploaded to codecov"
