name: Test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: emteknetnz/gha-tag-release@main
        with:
          tag: mytag
          delete_existing: true
          release: false
          body: >
            This is my body
            It has a few lines
            
            And a line break
            
            With "quotes" too
