name: Test
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Test
        uses: emteknetnz/gha-tag-release@main
        with:
          sha: 70249c7ae7183ca2bd314f7e7f53f06b5e5064b3
          tag: mytag
          delete_existing: true
          release: false
          github_token: ${{ github.token }}
          body: >
            This is my body
            It has a few lines
            
            And a line break
            
            With "quotes" too
